clear, clc, close all

alex = alexnet;
layers = alex.Layers;

inputSize = alex.Layers(1).InputSize;
allImages = imageDatastore('ObjectImages', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');
[trainingImages, valImages] = splitEachLabel(allImages, 0.7, 'randomized');
imageAugmenter = imageDataAugmenter( ...
    'RandRotation',[-20,20], ...
    'RandXTranslation',[-3 3], ...
    'RandYTranslation',[-3 3]);
augimgTrain = augmentedImageDatastore(inputSize(1:2),trainingImages, ...
    'DataAugmentation',imageAugmenter);
augimgValidation = augmentedImageDatastore(inputSize(1:2),valImages);
objectCategories = numel(categories(trainingImages.Labels));

layers(23) = fullyConnectedLayer(objectCategories, ...
    'WeightLearnRateFactor',20, ...
    'BiasLearnRateFactor',20); 
layers(24) = softmaxLayer;
layers(25) = classificationLayer;

%deepNetworkDesigner
%%
options = trainingOptions('adam', ... 
    'InitialLearnRate', 0.00005, ...
    'MaxEpochs', 12, ... 
    'MiniBatchSize', 16, ...
    'ValidationData',augimgValidation, ...
    'ValidationFrequency',2, ...
    'ValidationPatience',10, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',4, ...
    'Plots','training-progress', ...
    'Verbose',true, ...
    'VerboseFrequency',20);

alexTransfer = trainNetwork(augimgTrain, layers, options);

%%
[predictedLabels,probs] = classify(alexTransfer, augimgValidation); 
[accuracy, loss] = calcAccuracyLoss(predictedLabels, probs, valImages.Labels)

%%
confusion = plotConfusionMatrix(predictedLabels, valImages.Labels, accuracy, loss);

%%
plotPredictions(predictedLabels, probs, valImages);

%%
showMetrics(objectCategories, confusion, valImages.Labels);

%%
plotROC(valImages.Labels, probs);