clear,clc, close all

vgg = vgg16;
layers = vgg.Layers;

inputSize = vgg.Layers(1).InputSize;
allImages = imageDatastore('SCUImages', ...
    'IncludeSubfolders', true, ...
    'LabelSource', 'foldernames');
[trainingImages, valImages] = splitEachLabel(allImages, 0.7, 'randomized');
% imageAugmenter = imageDataAugmenter( ...
%     'RandRotation',[-20,20], ...
%     'RandXTranslation',[-3 3], ...
%     'RandYTranslation',[-3 3]);
augimgTrain = augmentedImageDatastore(inputSize(1:2),trainingImages);
augimgValidation = augmentedImageDatastore(inputSize(1:2),valImages);
objectCategories = numel(categories(trainingImages.Labels));

layers(39) = fullyConnectedLayer(objectCategories, ...
    'WeightLearnRateFactor',20, ...
    'BiasLearnRateFactor',20); 
layers(40) = softmaxLayer;
layers(41) = classificationLayer;

%deepNetworkDesigner
%%
options = trainingOptions('adam', ... 
    'InitialLearnRate', 0.00005, ...
    'MaxEpochs', 12, ... 
    'MiniBatchSize', 32, ...
    'ValidationData',augimgValidation, ...
    'ValidationFrequency',4, ...
    'ValidationPatience',10, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',4, ...
    'Plots','training-progress', ...
    'Verbose',true, ...
    'VerboseFrequency',20);

vggTransfer = trainNetwork(augimgTrain, layers, options);

%%
[predictedLabels,probs] = classify(vggTransfer, augimgValidation); 
[accuracy, loss] = calcAccuracyLoss(predictedLabels, probs, valImages.Labels)

%%
confusion = plotConfusionMatrix(predictedLabels, valImages.Labels, accuracy, loss);

%%
plotPredictions(predictedLabels, probs, valImages);

%%
showMetrics(objectCategories, confusion, valImages.Labels);

%%
plotROC(valImages.Labels, probs);